apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex-studio-preview-dev
resources:
- ../../../base-dex-studio
images:
- name: ghcr.io/thedataenginex/dex-studio
  newName: ghcr.io/thedataenginex/dex-studio
  newTag: sha-48261a65
patches:
- patch: |
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 100m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 250m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 1Gi
  target:
    kind: Deployment
    name: dex-studio
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: dev.preview.dex-studio.thedataenginex.org
  target:
    kind: Ingress
    name: dex-studio
commonLabels:
  environment: preview
