apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dex-studio-dev

resources:
  - ../../base-dex-studio

images:
  - name: ghcr.io/thedataenginex/dex-studio
    newTag: sha-00000000

patches:
  - target:
      kind: Deployment
      name: dex-studio
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

commonLabels:
  environment: dev
