apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex-studio-preview-feature-test-argocd
resources:
- ../../../../base-dex-studio
images:
- name: ghcr.io/thedataenginex/dex-studio
  newName: ghcr.io/thedataenginex/dex-studio
  newTag: sha-f63557d1
patches:
- patch: |
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 100m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 250m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
  target:
    kind: Deployment
    name: dex-studio
commonLabels:
  environment: preview
