apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: careerdex-stage

resources:
- ../../base-careerdex

images:
- name: ghcr.io/thedataenginex/careerdex
  newName: ghcr.io/thedataenginex/careerdex
  newTag: sha-fd40d725

patches:
- patch: |
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: careerdex

commonLabels:
  environment: stage
