name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: TheDataEngineX/.github/.github/workflows/release-please.yml@main
    secrets: inherit
