name: Security Scans

on:
  push:
    branches: [main, dev, stage]
  pull_request:
    branches: [main, dev, stage]

permissions:
  contents: read
  security-events: write

jobs:
  security:
    uses: TheDataEngineX/.github/.github/workflows/security.yml@main
    secrets: inherit
